# This is a basic workflow to help you get started with Actions
# Automation pipeline for validating the example for Opensource

name: OSS Validation

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["pages build and deployment"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" which validates the OSS kubeslice/charts repo
  build:
    if: github.repository == 'kubeslice/charts/charts/kubeslice-controller/ '
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script that will configure multiple kind clusters and interconnect them with KubeSlice.
        run: |
          sudo git clone https://github.com/ahmetb/kubectx /usr/local/kubectx
          sudo ln -s /usr/local/kubectx/kubectx /usr/local/bin/kubectx
          sudo ln -s /usr/local/kubectx/kubens /usr/local/bin/kubens
          
          sudo sysctl fs.inotify.max_user_instances=8192
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p
          
          sudo git clone https://github.com/kubeslice/examples.git
          cd examples/kind
          sudo bash kind.sh
